name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    env:
      GOPATH: ${{ github.workspace }}
      GITHUB_WORKSPACE: ${{ github.workspace }}/src/github.com/${{ github.repository }}
    steps:

    - name: Log env
      run: |
        echo ">>>> GITHUB_WORKSPACE:"
        echo $GITHUB_WORKSPACE
        echo ">>>> go path:"
        echo $GOPATH
        echo ">>>> pwd:"
        pwd

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        echo ">>>> GITHUB_WORKSPACE:"
        echo $GITHUB_WORKSPACE
        echo ">>>> go path:"
        echo $GOPATH
        echo ">>>> pwd:"
        pwd
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
