name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GOPATH: ${{ github.workspace }}
  APP: src/github.com/${{ github.repository }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ${{ env.APP }}

    - name: Get dependencies
      working-directory: ${{ github.workspace }}/${{ env.APP }}
      run: go get -v -t -d ./...

    - name: Build
      working-directory: ${{ github.workspace }}/${{ env.APP }}
      run: go build -v .

    - name: Test
      working-directory: ${{ github.workspace }}/${{ env.APP }}
      run: go test -v ./...
